[package]
name = "ecg_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.23.0"
eframe = "0.23.0"
egui_plot = "0.23.0"  # 添加绘图依赖
rustfft = "6.1.0"
num-complex = "0.4.4"
itertools = "0.11.0"